### PR TITLE
feat: AvatarHeader Snapshot in Tests

### PR DESCRIPTION
**Pull request by Frondelan**
# Note:
Added `AvatarHeader.test.js` in Tests to make a Snapshot of `AvatarHeader` component.

### CODE REVIEW

**Review by IdaszakDaniel — APPROVED** [review]

**Comment by Patys** [comment]
@Frondelan could you fix commit message to follow https://www.conventionalcommits.org/en/v1.0.0/ 
It will automatically generate changelog during release.

**Comment by Patys** [comment]
@Frondelan I mean commit, there is a pre-hook that should not allow you to commit without using proper commit message. Please rebase

ref #154

**Comment by pi0trpietruszewski** [comment]
To change commit name follow[this guide](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message)

**Comment by maciejBudzinskiNG** [comment]
@Frondelan Hi there! We would like to merge your changes, but could you please change the commit name according to the previous comment?

**Pull request merged**
