### PR TITLE
#149 replace renderBody to children in predefined components

### PR DESCRIPTION
**Pull request by bobsany16**
- Replaced renderBody prop with children in `AvatarHeader`, `DetailsHeader`, and `TabbedHeader` (this one wasn't mention in the issue #149 but I thought it'd make sense that all 3 predefined components should be consistent) 
- Added the children prop in docs and `index.d.ts`

**Note** 
- I was unsure if I should have defined a defaultProp for children or not in all 3 headers. I saw that while `renderBody` had a defaultProp of `<RenderContent user={} />` or `<RenderContent title="" />`
- Please let me know if I should fix this 😁

### CODE REVIEW

**Comment by pi0trpietruszewski** [comment]
I believe we need pass default component. Without it there will be no content in scroll. @Patys what do you think?

**Comment by Patys** [comment]
It's also breaking change, I would like to add it additionally and mark old renderBody as deprecated so people would be able to move to new functionality

**Review by Patys — CHANGES_REQUESTED** [review]
It's also breaking change, I would like to add it additionally and mark old renderBody as deprecated so people would be able to move to new functionality

**Comment by bobsany16** [comment]
Will work on it! Been a bit busy

**Comment by Patys** [comment]
@bobsany16 So users should be able to update and it won't require any additional work for them to use new version, also if they use renderBody they should get yellow box warning about deprecation and moving to children

**Comment by bobsany16** [comment]
@Patys was able to do what you asked, except for marking it deprecated. When researching, the ideal scenario is that we would declare the `renderBody` prop as deprecated but since this would likely console.warn(), this would fail tests. Any ideas ?

**Comment by Tilenozz** [comment]
When this feature will be avaiable ?

**Review by IdaszakDaniel — APPROVED** [review]

**Pull request merged**
